settings:
  data_dir: /eos/user/y/yukaiz/FT_Run3/data/DFEI_LHCb_LHCbcollision_normed_pt_data/
  sample: [00342629_Bs_Jpsiphi, 00342442_inclusive, 00338627_Bd_JpsiKst]
  nfiles: [1, 1, 1]
  batch_size: 128
  lr: 1e-3
  weight_decay: 1e-5
  epochs: 1
  gacc: 1
  ngpu: 1
  ncpu: 8
  graph_mode: None
  node_sel: 'true'
  pv_model: 'true'
inference:
  FT: true
  FT_weights: false
  frag: false
  frag_weights: false
  edge_prune_thr: 0.9
  node_prune_thr: 0.9
evaluate:
  sample: [00342629_Bs_Jpsiphi, 00342638_Bs_Jpsiphi]
  nfiles: [1, 1]
  over_write: ''
IFT:
  dfei_model: None
  use_pid: 'True'
  cpt: None
  node_types: [tracks, pvs]
  edge_types: [tracks_tracks, tracks_pvs]
  encoder:
    usage: true
    global:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    tracks:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    pvs:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    tracks_tracks:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    tracks_pvs:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
  GNblocks:
    nBlocks: 2
    use_globals: true
    use_node_weights: true
    use_edge_weights: true
    weighted_pass: true
    MLP_forward:
      layers: [-1, 128, 128, 16]
      norm: graph_norm
      dropout: 0.01
    MLP_infer:
      layers: [-1, 16, 16, 16, 1]
      norm: graph_norm
      dropout: 0.01
  decoder:
    usage: true
    global:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    tracks:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    pvs:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    tracks_tracks:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
    tracks_pvs:
      layers: [-1, 128, 128, 16]
      norm: [graph_norm, graph_norm]
      dropout: 0.01
  op_trafo:
    usage: true
    tr_tr: None
    tr_pv: None
    tr: 3
    pv: None
    global: None
    MLP:
      layers: [-1, -1]
      norm: graph_norm
      dropout: 0.01
