model:
  DFEI:
    usage: True
    node_types: [ 'tracks', 'pvs' ]
    edge_types: [ "tracks_tracks", "tracks_pvs" ]
    encoder:
      usage: True
      vars: [ "global", "tracks" ,"tracks_tracks", "pvs", "tracks_pvs" ] # variables which are encoded
      MLP:
        layers: [ -1, 128, 128, 16 ]
        norm: ["batch_norm"]
        dropout: 0.01
    GNblocks:
      nBlocks: 2
      FTlayers: 0
      use_globals: True
      use_node_weights: True # MLP to infer a node weight, also necessary for node pruning
      use_edge_weights: True # MLP to infer an edge weight, also necessary for edge pruning
      weighted_pass: True # Whether to pass the weights, requires above
      MLP_forward:
        layers: [ -1, 128, 128, 16 ]
        norm: "batch_norm" # or layers - 2 specific norms
        dropout: 0.01 # or layers - 1 specific dropout values
      MLP_infer:
        layers: [ -1, 16, 16, 16, 1 ]
        norm: "batch_norm"
        dropout: 0.01
    decoder:
      usage: True
      vars: [ "global", "tracks" ,"tracks_tracks" , "pvs", "tracks_pvs" ] # variables which are encoded
      MLP:
        layers: [ -1, 128, 128, 16 ]
        norm: "batch_norm"
        dropout: 0.01
    op_trafo: # transforms output to desired dimension
      usage: True
      tr_tr: 4  # Output dim of edges, 4 for LCA edges
      tr_pv: None
      tr: 32  # Hyperspace representation to pass to FT part
      pv: None
      global: None
      MLP:
        layers: [ -1, -1 ]
        norm: "batch_norm"
        dropout: 0.01

  FT_inferer: # FT model
    usage: False
    node_types: [ 'tracks', 'pvs' ]
    edge_types: [ "tracks_tracks", "tracks_pvs" ]
    encoder:
      usage: True
      vars: [ "global", "tracks" ,"tracks_tracks", "pvs", "tracks_pvs" ] # variables which are encoded
      MLP:
        layers: [ -1, 128, 128, 16 ]
        norm: "batch_norm"
        dropout: 0.01
    GNblocks:
      nBlocks: 1
      FTlayers: 0
      use_globals: True
      use_node_weights: True # MLP to infer a node weight, also necessary for node pruning
      use_edge_weights: True # MLP to infer an edge weight, also necessary for edge pruning
      weighted_pass: True # Whether to pass the weights, requires above
      MLP_forward:
        layers: [ -1, 128, 128, 16 ]
        norm: "batch_norm"
        dropout: 0.01
      MLP_infer:
        layers: [ -1, 16, 16, 16, 1 ]
        norm: "batch_norm"
        dropout: 0.01
    decoder:
      usage: True
      vars: [ "global", "tracks" ,"tracks_tracks" , "pvs", "tracks_pvs" ] # variables which are encoded
      MLP:
        layers: [ -1, 128, 128, 16 ]
        norm: "batch_norm"
        dropout: 0.01
    op_trafo: # transforms output to desired dimension
      usage: True
      tr_tr: None
      tr_pv: None
      tr: 3  # FT output dim
      pv: None
      global: None
      MLP:
        layers: [ -1, -1 ]
        norm: "batch_norm"
        dropout: 0.01

data_dir: "/eos/user/y/yukaiz/DFEI_data/DFEI_pythia_single_pp_normed_graph/"

training:
  graph_mode: "None"  # true: True graph
  node_sel: "true"  # Conditioned on graph_mode
  sample: [ "Bs_Jpsiphi", "Bd_JpsiKs", "inclusive" ]
  nfiles: [ 1, 0, 0 ]
  batch_size: 128
  epochs: 100
  gacc: 1  # gradient accumulation if using smaller batch size
  ngpu: 1  # need roughly 40 Gb for bs of 12
  ncpu: 8  # need roughly 128Gb cpu memory
  cpt:
    model: "None" # None or 10_bis
  cw: False # Flag if weights need to be calculated or not
  infer:
    LCA: True
    node_prune: True
    edge_prune: True
    FT: True
    frag: False
  weights:
    LCA: True
    node: True
    edge: True
    FT: True
    frag: False


evaluate:
  sample: "Bs_Jpsiphi"
  nfiles: 1
