# Global settings
settings:
  data_dir: "/eos/user/y/yukaiz/DFEI_data/DFEI_pythia_nu7p6_onehot_normed_pt_data"
  sample: [ "Bs_Jpsiphi", "Bd_JpsiKs", "inclusive" ]
  nfiles: [ 80, 80, 200 ]
  batch_size: 16
  lr: 1e-3
  weight_decay: 1e-5
  epochs: 100
  gacc: 4  # gradient accumulation if using smaller batch size
  ngpu: 1  # need roughly 40 Gb for bs of 12
  ncpu: 8  # NCPUs for data loader
  graph_mode: "None"  # Apply pruning on initial graph, can use true_frag for true graph with frag
  node_sel: "true"  # way of apply pruning on initial graph: true, default, zeros
  edge_prune_thr: 0.1  # Edge prune threshold during reco
  node_prune_thr: 0.1  # Node prune threshold during reco

inference:
  LCA: True
  LCA_weights: True
  node_prune: True
  node_prune_weights: True
  edge_prune: True
  edge_prune_weights: True
  FT: True
  FT_weights: False
  frag: False
  frag_weights: False
  pv_asso: True
  pv_asso_weights: True


evaluate:
  sample: "Bs_Jpsiphi"
  nfiles: 80


DFEI:
  mode: "train"  # or absolute file path: train
  cpt: "None"
  node_types: [ 'tracks', 'pvs' ]  # Graph node settings
  edge_types: [ "tracks_tracks", "tracks_pvs" ]  # Graph edge settings
  encoder:
    usage: True
    global:
      layers: [ -1, 128, 128, 16 ]
      norm: ["graph_norm", "None"] # pass single string or [layers - 2 specific norms]
      dropout: 0.01 # pass single float or [layers - 1 specific dropout values]
    tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
  GNblocks:
    nBlocks: 2
    use_globals: True
    use_node_weights: True # MLP to infer a node weight, also necessary for node pruning
    use_edge_weights: True # MLP to infer an edge weight, also necessary for edge pruning
    weighted_pass: True # Whether to pass the weights, requires above
    MLP_forward:
      layers: [ -1, 128, 128, 16 ]
      norm: "graph_norm"
      dropout: 0.01
    MLP_infer:
      layers: [ -1, 16, 16, 16, 1 ]
      norm: "graph_norm"
      dropout: 0.01
  decoder:
    usage: True
    global:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ] # pass single string or [layers - 2 specific norms]
      dropout: 0.01 # pass single float or [layers - 1 specific dropout values]
    tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
  op_trafo: # transforms output to desired dimension
    usage: True
    tr_tr: 4  # Output dim of edges, 4 for LCA edges
    tr_pv: None
    tr: None
    pv: None
    global: None
    MLP:
      layers: [ -1, -1 ]
      norm: "graph_norm"
      dropout: 0.01

IFT:
  mode: "None"
  cpt: None # Version number of None
  dfei_model: None # Version number or None
  node_types: [ 'tracks', 'pvs' ]  # Graph node settings
  edge_types: [ "tracks_tracks", "tracks_pvs" ]  # Graph edge settings
  encoder:
    usage: True
    global:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ] # pass single string or [layers - 2 specific norms]
      dropout: 0.01 # pass single float or [layers - 1 specific dropout values]
    tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
  GNblocks:
    nBlocks: 2
    use_globals: True
    use_node_weights: True # MLP to infer a node weight, also necessary for node pruning
    use_edge_weights: True # MLP to infer an edge weight, also necessary for edge pruning
    weighted_pass: True # Whether to pass the weights, requires above
    MLP_forward:
      layers: [ -1, 128, 128, 16 ]
      norm: "graph_norm"
      dropout: 0.01
    MLP_infer:
      layers: [ -1, 16, 16, 16, 1 ]
      norm: "graph_norm"
      dropout: 0.01
  decoder:
    usage: True
    global:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ] # pass single string or [layers - 2 specific norms]
      dropout: 0.01 # pass single float or [layers - 1 specific dropout values]
    tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
    tracks_pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "graph_norm" ]
      dropout: 0.01
  op_trafo: # transforms output to desired dimension
    usage: True
    tr_tr: None
    tr_pv: None
    tr: 3  # FT output
    pv: None
    global: None
    MLP:
      layers: [ -1, -1 ]
      norm: "graph_norm"
      dropout: 0.01

