settings:
  # Input file information
  data_dir: "/eos/user/y/yukaiz/DFEI_IFT_Run3/test_data/MC_normed/"
  sample: [ "BdToDPi_00338410", 'BdToJpsiKst_00338627', 'BsToDsPi_00338392', 'BsToJpsiPhi_00342629', 'BuToJpsiK_00338624']
  nfiles: [200, 200, 200, 200, 200,]
  # Training settings
  batch_size: 64
  lr: 1e-3
  weight_decay: 1e-5
  epochs: 200
  gacc: 1  # Accumulating number of mini batches before step
  ngpu: 1  # Number of GPUs used for training
  ncpu: 16  # Number CPUs used for multithreading/data loader,
  # Preselection filters
  graph_mode: "None"  # Apply pruning on initial graph: "true", "true_frag" "None"
  node_sel: "true"  # Pruner used to apply the graph mode above: "true", "zeros", "default"
  pv_model: "None" # Initial PV association: DFEI_model_number (auto select bis), "true", "ip", "None"
  pv_model_name: "None" #  name to specify the model, "None" (best model auto selected)
  # Calirbation for FT
  calibration: false
  # Domain adaptation
  domain_adapt: false
  da_data_dir: "/eos/user/y/yukaiz/DFEI_IFT/data/DFEI_LHCb_data_normed_pt_data/"
  da_sample: ["1239876_Bu_JpsiK"]
  da_nfiles: [1]

inference:
  LCA: true
  LCA_weights: false
  node_prune: true
  node_prune_weights: true
  edge_prune: true
  edge_prune_weights: true
  pv_asso: true
  pv_asso_weights: true
  # Defining thresholds to remove bkg edges and nodes before reconstruction
  edge_prune_thr: 0.1  # Edge prune threshold during reco
  node_prune_thr: 0.1  # Node prune threshold during reco


evaluate:
  sample: [ "BsToJpsiPhi_00342629" ]
  nfiles: [ 10 ]
  over_write: "" # argument to overwrite the output names to rerun safely the same sample: "" for no overwrite


DFEI:
  use_pid: true # Adding pid information in forward pass: true, false
  cpt: 'None' # Loading checkpoint to continue training: "None", DFEI_version_number (select the last model and just continue)
  cpt_name: "None" # "bis" (for selecting the best model), "best-epoch.ckpt", "None"
  node_types: [ 'tracks', 'pvs' ]  # Graph node settings
  edge_types: [ "tracks_tracks", "tracks_pvs" ]  # Graph edge settings
  encoder:
    usage: true
    global:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "None" ] # pass single string or [layers - 2 specific norms]
      dropout: 0.01 # pass single float or [layers - 1 specific dropout values]
    tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "None" ]
      dropout: 0.01
    pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "None" ]
      dropout: 0.01
    tracks_tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "None" ]
      dropout: 0.01
    tracks_pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "graph_norm", "None" ]
      dropout: 0.01
  GNblocks:
    nBlocks: 4
    use_globals: true
    use_node_weights: true # MLP to infer a node weight, also necessary for node pruning
    use_edge_weights: true # MLP to infer an edge weight, also necessary for edge pruning
    weighted_pass: true # Whether to pass the weights, requires above
    MLP_forward:
      layers: [ -1, 128, 128, 16 ]
      norm: "None"
      dropout: 0.01
    MLP_infer:
      layers: [ -1, 16, 16, 16, 1 ]
      norm: "None"
      dropout: 0.01
  decoder:
    usage: True
    global:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "None", "None" ] # pass single string or [layers - 2 specific norms]
      dropout: 0.01 # pass single float or [layers - 1 specific dropout values]
    tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "None", "None" ]
      dropout: 0.01
    pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "None", "None" ]
      dropout: 0.01
    tracks_tracks:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "None", "None" ]
      dropout: 0.01
    tracks_pvs:
      layers: [ -1, 128, 128, 16 ]
      norm: [ "None", "None" ]
      dropout: 0.01
  op_trafo: # transforms output to desired dimension
    usage: true
    tr_tr: 4  # Output dim of edges, 4 for LCA edges
    tr_pv: None
    tr: None
    pv: None
    global: None
    MLP:
      layers: [ -1, -1 ]
      norm: "None"
      dropout: 0.01
  # Domain adaptation
  domain_adapt:
    scatter_func: "mean"
    MLP:
      layers: [ -1, 128, 128, 16, 1 ]
      norm: "None"
      dropout: 0.01


